import { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";

import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { LangProvider } from "@/contexts/LangContext";

const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${cormorantGaramond.className} min-h-screen flex flex-col`}
      >
        <LangProvider>
          <Header />
          {children}
          <Footer />
        </LangProvider>
      </body>
    </html>
  );
}
